package com.mycompany.myproject.test.integration.java;/*
 * Copyright 2013 Red Hat, Inc.
 *
 * Red Hat licenses this file to you under the Apache License, version 2.0
 * (the "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * @author <a href="http://tfox.org">Tim Fox</a>
 */

import org.junit.Test;
import org.vertx.java.core.AsyncResult;
import org.vertx.java.core.AsyncResultHandler;
import org.vertx.java.core.Handler;
import org.vertx.java.core.eventbus.Message;
import org.vertx.java.core.http.HttpClientResponse;
import org.vertx.java.core.http.HttpServerRequest;
import org.vertx.testtools.TestVerticle;
import org.vertx.testtools.VertxAssert;

import static org.vertx.testtools.VertxAssert.*;

/**
 * Example Java integration test that deploys the module that this project builds.
 *
 * Quite often in integration tests you want to deploy the same module for all tests and you don't want tests
 * to start before the module has been deployed.
 *
 * This test demonstrates how to do that.
 */
public class ModuleIntegrationTest extends TestVerticle {

  @Test
  public void testPing() {
    container.logger().info("in testPing()");
    vertx.eventBus().send("ping-address", "ping!", new Handler<Message<String>>() {
      @Override
      public void handle(Message<String> reply) {
        assertEquals("pong!", reply.body());

        /*
        If we get here, the test is complete
        You must always call `testComplete()` at the end. Remember that testing is *asynchronous* so
        we cannot assume the test is complete by the time the test method has finished executing like
        in standard synchronous tests
        */
        testComplete();
      }
    });
  }

  @Test
  public void testSomethingElse() {
    // Whatever
    testComplete();
  }

  @Test public void testMemory0() { testComplete(); }
  @Test public void testMemory1() { testComplete(); }
  @Test public void testMemory2() { testComplete(); }
  @Test public void testMemory3() { testComplete(); }
  @Test public void testMemory4() { testComplete(); }
  @Test public void testMemory5() { testComplete(); }
  @Test public void testMemory6() { testComplete(); }
  @Test public void testMemory7() { testComplete(); }
  @Test public void testMemory8() { testComplete(); }
  @Test public void testMemory9() { testComplete(); }
  @Test public void testMemory10() { testComplete(); }
  @Test public void testMemory11() { testComplete(); }
  @Test public void testMemory12() { testComplete(); }
  @Test public void testMemory13() { testComplete(); }
  @Test public void testMemory14() { testComplete(); }
  @Test public void testMemory15() { testComplete(); }
  @Test public void testMemory16() { testComplete(); }
  @Test public void testMemory17() { testComplete(); }
  @Test public void testMemory18() { testComplete(); }
  @Test public void testMemory19() { testComplete(); }
  @Test public void testMemory20() { testComplete(); }
  @Test public void testMemory21() { testComplete(); }
  @Test public void testMemory22() { testComplete(); }
  @Test public void testMemory23() { testComplete(); }
  @Test public void testMemory24() { testComplete(); }
  @Test public void testMemory25() { testComplete(); }
  @Test public void testMemory26() { testComplete(); }
  @Test public void testMemory27() { testComplete(); }
  @Test public void testMemory28() { testComplete(); }
  @Test public void testMemory29() { testComplete(); }
  @Test public void testMemory30() { testComplete(); }
  @Test public void testMemory31() { testComplete(); }
  @Test public void testMemory32() { testComplete(); }
  @Test public void testMemory33() { testComplete(); }
  @Test public void testMemory34() { testComplete(); }
  @Test public void testMemory35() { testComplete(); }
  @Test public void testMemory36() { testComplete(); }
  @Test public void testMemory37() { testComplete(); }
  @Test public void testMemory38() { testComplete(); }
  @Test public void testMemory39() { testComplete(); }
  @Test public void testMemory40() { testComplete(); }
  @Test public void testMemory41() { testComplete(); }
  @Test public void testMemory42() { testComplete(); }
  @Test public void testMemory43() { testComplete(); }
  @Test public void testMemory44() { testComplete(); }
  @Test public void testMemory45() { testComplete(); }
  @Test public void testMemory46() { testComplete(); }
  @Test public void testMemory47() { testComplete(); }
  @Test public void testMemory48() { testComplete(); }
  @Test public void testMemory49() { testComplete(); }
  @Test public void testMemory50() { testComplete(); }
  @Test public void testMemory51() { testComplete(); }
  @Test public void testMemory52() { testComplete(); }
  @Test public void testMemory53() { testComplete(); }
  @Test public void testMemory54() { testComplete(); }
  @Test public void testMemory55() { testComplete(); }
  @Test public void testMemory56() { testComplete(); }
  @Test public void testMemory57() { testComplete(); }
  @Test public void testMemory58() { testComplete(); }
  @Test public void testMemory59() { testComplete(); }
  @Test public void testMemory60() { testComplete(); }
  @Test public void testMemory61() { testComplete(); }
  @Test public void testMemory62() { testComplete(); }
  @Test public void testMemory63() { testComplete(); }
  @Test public void testMemory64() { testComplete(); }
  @Test public void testMemory65() { testComplete(); }
  @Test public void testMemory66() { testComplete(); }
  @Test public void testMemory67() { testComplete(); }
  @Test public void testMemory68() { testComplete(); }
  @Test public void testMemory69() { testComplete(); }
  @Test public void testMemory70() { testComplete(); }
  @Test public void testMemory71() { testComplete(); }
  @Test public void testMemory72() { testComplete(); }
  @Test public void testMemory73() { testComplete(); }
  @Test public void testMemory74() { testComplete(); }
  @Test public void testMemory75() { testComplete(); }
  @Test public void testMemory76() { testComplete(); }
  @Test public void testMemory77() { testComplete(); }
  @Test public void testMemory78() { testComplete(); }
  @Test public void testMemory79() { testComplete(); }
  @Test public void testMemory80() { testComplete(); }
  @Test public void testMemory81() { testComplete(); }
  @Test public void testMemory82() { testComplete(); }
  @Test public void testMemory83() { testComplete(); }
  @Test public void testMemory84() { testComplete(); }
  @Test public void testMemory85() { testComplete(); }
  @Test public void testMemory86() { testComplete(); }
  @Test public void testMemory87() { testComplete(); }
  @Test public void testMemory88() { testComplete(); }
  @Test public void testMemory89() { testComplete(); }
  @Test public void testMemory90() { testComplete(); }
  @Test public void testMemory91() { testComplete(); }
  @Test public void testMemory92() { testComplete(); }
  @Test public void testMemory93() { testComplete(); }
  @Test public void testMemory94() { testComplete(); }
  @Test public void testMemory95() { testComplete(); }
  @Test public void testMemory96() { testComplete(); }
  @Test public void testMemory97() { testComplete(); }
  @Test public void testMemory98() { testComplete(); }
  @Test public void testMemory99() { testComplete(); }
  @Test public void testMemory100() { testComplete(); }
  @Test public void testMemory101() { testComplete(); }
  @Test public void testMemory102() { testComplete(); }
  @Test public void testMemory103() { testComplete(); }
  @Test public void testMemory104() { testComplete(); }
  @Test public void testMemory105() { testComplete(); }
  @Test public void testMemory106() { testComplete(); }
  @Test public void testMemory107() { testComplete(); }
  @Test public void testMemory108() { testComplete(); }
  @Test public void testMemory109() { testComplete(); }
  @Test public void testMemory110() { testComplete(); }
  @Test public void testMemory111() { testComplete(); }
  @Test public void testMemory112() { testComplete(); }
  @Test public void testMemory113() { testComplete(); }
  @Test public void testMemory114() { testComplete(); }
  @Test public void testMemory115() { testComplete(); }
  @Test public void testMemory116() { testComplete(); }
  @Test public void testMemory117() { testComplete(); }
  @Test public void testMemory118() { testComplete(); }
  @Test public void testMemory119() { testComplete(); }
  @Test public void testMemory120() { testComplete(); }
  @Test public void testMemory121() { testComplete(); }
  @Test public void testMemory122() { testComplete(); }
  @Test public void testMemory123() { testComplete(); }
  @Test public void testMemory124() { testComplete(); }
  @Test public void testMemory125() { testComplete(); }
  @Test public void testMemory126() { testComplete(); }
  @Test public void testMemory127() { testComplete(); }
  @Test public void testMemory128() { testComplete(); }
  @Test public void testMemory129() { testComplete(); }
  @Test public void testMemory130() { testComplete(); }
  @Test public void testMemory131() { testComplete(); }
  @Test public void testMemory132() { testComplete(); }
  @Test public void testMemory133() { testComplete(); }
  @Test public void testMemory134() { testComplete(); }
  @Test public void testMemory135() { testComplete(); }
  @Test public void testMemory136() { testComplete(); }
  @Test public void testMemory137() { testComplete(); }
  @Test public void testMemory138() { testComplete(); }
  @Test public void testMemory139() { testComplete(); }
  @Test public void testMemory140() { testComplete(); }
  @Test public void testMemory141() { testComplete(); }
  @Test public void testMemory142() { testComplete(); }
  @Test public void testMemory143() { testComplete(); }
  @Test public void testMemory144() { testComplete(); }
  @Test public void testMemory145() { testComplete(); }
  @Test public void testMemory146() { testComplete(); }
  @Test public void testMemory147() { testComplete(); }
  @Test public void testMemory148() { testComplete(); }
  @Test public void testMemory149() { testComplete(); }
  @Test public void testMemory150() { testComplete(); }
  @Test public void testMemory151() { testComplete(); }
  @Test public void testMemory152() { testComplete(); }
  @Test public void testMemory153() { testComplete(); }
  @Test public void testMemory154() { testComplete(); }
  @Test public void testMemory155() { testComplete(); }
  @Test public void testMemory156() { testComplete(); }
  @Test public void testMemory157() { testComplete(); }
  @Test public void testMemory158() { testComplete(); }
  @Test public void testMemory159() { testComplete(); }
  @Test public void testMemory160() { testComplete(); }
  @Test public void testMemory161() { testComplete(); }
  @Test public void testMemory162() { testComplete(); }
  @Test public void testMemory163() { testComplete(); }
  @Test public void testMemory164() { testComplete(); }
  @Test public void testMemory165() { testComplete(); }
  @Test public void testMemory166() { testComplete(); }
  @Test public void testMemory167() { testComplete(); }
  @Test public void testMemory168() { testComplete(); }
  @Test public void testMemory169() { testComplete(); }
  @Test public void testMemory170() { testComplete(); }
  @Test public void testMemory171() { testComplete(); }
  @Test public void testMemory172() { testComplete(); }
  @Test public void testMemory173() { testComplete(); }
  @Test public void testMemory174() { testComplete(); }
  @Test public void testMemory175() { testComplete(); }
  @Test public void testMemory176() { testComplete(); }
  @Test public void testMemory177() { testComplete(); }
  @Test public void testMemory178() { testComplete(); }
  @Test public void testMemory179() { testComplete(); }
  @Test public void testMemory180() { testComplete(); }
  @Test public void testMemory181() { testComplete(); }
  @Test public void testMemory182() { testComplete(); }
  @Test public void testMemory183() { testComplete(); }
  @Test public void testMemory184() { testComplete(); }
  @Test public void testMemory185() { testComplete(); }
  @Test public void testMemory186() { testComplete(); }
  @Test public void testMemory187() { testComplete(); }
  @Test public void testMemory188() { testComplete(); }
  @Test public void testMemory189() { testComplete(); }
  @Test public void testMemory190() { testComplete(); }
  @Test public void testMemory191() { testComplete(); }
  @Test public void testMemory192() { testComplete(); }
  @Test public void testMemory193() { testComplete(); }
  @Test public void testMemory194() { testComplete(); }
  @Test public void testMemory195() { testComplete(); }
  @Test public void testMemory196() { testComplete(); }
  @Test public void testMemory197() { testComplete(); }
  @Test public void testMemory198() { testComplete(); }
  @Test public void testMemory199() { testComplete(); }
  @Test public void testMemory200() { testComplete(); }
  @Test public void testMemory201() { testComplete(); }
  @Test public void testMemory202() { testComplete(); }
  @Test public void testMemory203() { testComplete(); }
  @Test public void testMemory204() { testComplete(); }
  @Test public void testMemory205() { testComplete(); }
  @Test public void testMemory206() { testComplete(); }
  @Test public void testMemory207() { testComplete(); }
  @Test public void testMemory208() { testComplete(); }
  @Test public void testMemory209() { testComplete(); }
  @Test public void testMemory210() { testComplete(); }
  @Test public void testMemory211() { testComplete(); }
  @Test public void testMemory212() { testComplete(); }
  @Test public void testMemory213() { testComplete(); }
  @Test public void testMemory214() { testComplete(); }
  @Test public void testMemory215() { testComplete(); }
  @Test public void testMemory216() { testComplete(); }
  @Test public void testMemory217() { testComplete(); }
  @Test public void testMemory218() { testComplete(); }
  @Test public void testMemory219() { testComplete(); }
  @Test public void testMemory220() { testComplete(); }
  @Test public void testMemory221() { testComplete(); }
  @Test public void testMemory222() { testComplete(); }
  @Test public void testMemory223() { testComplete(); }
  @Test public void testMemory224() { testComplete(); }
  @Test public void testMemory225() { testComplete(); }
  @Test public void testMemory226() { testComplete(); }
  @Test public void testMemory227() { testComplete(); }
  @Test public void testMemory228() { testComplete(); }
  @Test public void testMemory229() { testComplete(); }
  @Test public void testMemory230() { testComplete(); }
  @Test public void testMemory231() { testComplete(); }
  @Test public void testMemory232() { testComplete(); }
  @Test public void testMemory233() { testComplete(); }
  @Test public void testMemory234() { testComplete(); }
  @Test public void testMemory235() { testComplete(); }
  @Test public void testMemory236() { testComplete(); }
  @Test public void testMemory237() { testComplete(); }
  @Test public void testMemory238() { testComplete(); }
  @Test public void testMemory239() { testComplete(); }
  @Test public void testMemory240() { testComplete(); }
  @Test public void testMemory241() { testComplete(); }
  @Test public void testMemory242() { testComplete(); }
  @Test public void testMemory243() { testComplete(); }
  @Test public void testMemory244() { testComplete(); }
  @Test public void testMemory245() { testComplete(); }
  @Test public void testMemory246() { testComplete(); }
  @Test public void testMemory247() { testComplete(); }
  @Test public void testMemory248() { testComplete(); }
  @Test public void testMemory249() { testComplete(); }
  @Test public void testMemory250() { testComplete(); }
  @Test public void testMemory251() { testComplete(); }
  @Test public void testMemory252() { testComplete(); }
  @Test public void testMemory253() { testComplete(); }
  @Test public void testMemory254() { testComplete(); }
  @Test public void testMemory255() { testComplete(); }
  @Test public void testMemory256() { testComplete(); }
  @Test public void testMemory257() { testComplete(); }
  @Test public void testMemory258() { testComplete(); }
  @Test public void testMemory259() { testComplete(); }
  @Test public void testMemory260() { testComplete(); }
  @Test public void testMemory261() { testComplete(); }
  @Test public void testMemory262() { testComplete(); }
  @Test public void testMemory263() { testComplete(); }
  @Test public void testMemory264() { testComplete(); }
  @Test public void testMemory265() { testComplete(); }
  @Test public void testMemory266() { testComplete(); }
  @Test public void testMemory267() { testComplete(); }
  @Test public void testMemory268() { testComplete(); }
  @Test public void testMemory269() { testComplete(); }
  @Test public void testMemory270() { testComplete(); }
  @Test public void testMemory271() { testComplete(); }
  @Test public void testMemory272() { testComplete(); }
  @Test public void testMemory273() { testComplete(); }
  @Test public void testMemory274() { testComplete(); }
  @Test public void testMemory275() { testComplete(); }
  @Test public void testMemory276() { testComplete(); }
  @Test public void testMemory277() { testComplete(); }
  @Test public void testMemory278() { testComplete(); }
  @Test public void testMemory279() { testComplete(); }
  @Test public void testMemory280() { testComplete(); }
  @Test public void testMemory281() { testComplete(); }
  @Test public void testMemory282() { testComplete(); }
  @Test public void testMemory283() { testComplete(); }
  @Test public void testMemory284() { testComplete(); }
  @Test public void testMemory285() { testComplete(); }
  @Test public void testMemory286() { testComplete(); }
  @Test public void testMemory287() { testComplete(); }
  @Test public void testMemory288() { testComplete(); }
  @Test public void testMemory289() { testComplete(); }
  @Test public void testMemory290() { testComplete(); }
  @Test public void testMemory291() { testComplete(); }
  @Test public void testMemory292() { testComplete(); }
  @Test public void testMemory293() { testComplete(); }
  @Test public void testMemory294() { testComplete(); }
  @Test public void testMemory295() { testComplete(); }
  @Test public void testMemory296() { testComplete(); }
  @Test public void testMemory297() { testComplete(); }
  @Test public void testMemory298() { testComplete(); }
  @Test public void testMemory299() { testComplete(); }
  @Test public void testMemory300() { testComplete(); }
  @Test public void testMemory301() { testComplete(); }
  @Test public void testMemory302() { testComplete(); }
  @Test public void testMemory303() { testComplete(); }
  @Test public void testMemory304() { testComplete(); }
  @Test public void testMemory305() { testComplete(); }
  @Test public void testMemory306() { testComplete(); }
  @Test public void testMemory307() { testComplete(); }
  @Test public void testMemory308() { testComplete(); }
  @Test public void testMemory309() { testComplete(); }
  @Test public void testMemory310() { testComplete(); }
  @Test public void testMemory311() { testComplete(); }
  @Test public void testMemory312() { testComplete(); }
  @Test public void testMemory313() { testComplete(); }
  @Test public void testMemory314() { testComplete(); }
  @Test public void testMemory315() { testComplete(); }
  @Test public void testMemory316() { testComplete(); }
  @Test public void testMemory317() { testComplete(); }
  @Test public void testMemory318() { testComplete(); }
  @Test public void testMemory319() { testComplete(); }
  @Test public void testMemory320() { testComplete(); }
  @Test public void testMemory321() { testComplete(); }
  @Test public void testMemory322() { testComplete(); }
  @Test public void testMemory323() { testComplete(); }
  @Test public void testMemory324() { testComplete(); }
  @Test public void testMemory325() { testComplete(); }
  @Test public void testMemory326() { testComplete(); }
  @Test public void testMemory327() { testComplete(); }
  @Test public void testMemory328() { testComplete(); }
  @Test public void testMemory329() { testComplete(); }
  @Test public void testMemory330() { testComplete(); }
  @Test public void testMemory331() { testComplete(); }
  @Test public void testMemory332() { testComplete(); }
  @Test public void testMemory333() { testComplete(); }
  @Test public void testMemory334() { testComplete(); }
  @Test public void testMemory335() { testComplete(); }
  @Test public void testMemory336() { testComplete(); }
  @Test public void testMemory337() { testComplete(); }
  @Test public void testMemory338() { testComplete(); }
  @Test public void testMemory339() { testComplete(); }
  @Test public void testMemory340() { testComplete(); }
  @Test public void testMemory341() { testComplete(); }
  @Test public void testMemory342() { testComplete(); }
  @Test public void testMemory343() { testComplete(); }
  @Test public void testMemory344() { testComplete(); }
  @Test public void testMemory345() { testComplete(); }
  @Test public void testMemory346() { testComplete(); }
  @Test public void testMemory347() { testComplete(); }
  @Test public void testMemory348() { testComplete(); }
  @Test public void testMemory349() { testComplete(); }
  @Test public void testMemory350() { testComplete(); }
  @Test public void testMemory351() { testComplete(); }
  @Test public void testMemory352() { testComplete(); }
  @Test public void testMemory353() { testComplete(); }
  @Test public void testMemory354() { testComplete(); }
  @Test public void testMemory355() { testComplete(); }
  @Test public void testMemory356() { testComplete(); }
  @Test public void testMemory357() { testComplete(); }
  @Test public void testMemory358() { testComplete(); }
  @Test public void testMemory359() { testComplete(); }
  @Test public void testMemory360() { testComplete(); }
  @Test public void testMemory361() { testComplete(); }
  @Test public void testMemory362() { testComplete(); }
  @Test public void testMemory363() { testComplete(); }
  @Test public void testMemory364() { testComplete(); }
  @Test public void testMemory365() { testComplete(); }
  @Test public void testMemory366() { testComplete(); }
  @Test public void testMemory367() { testComplete(); }
  @Test public void testMemory368() { testComplete(); }
  @Test public void testMemory369() { testComplete(); }
  @Test public void testMemory370() { testComplete(); }
  @Test public void testMemory371() { testComplete(); }
  @Test public void testMemory372() { testComplete(); }
  @Test public void testMemory373() { testComplete(); }
  @Test public void testMemory374() { testComplete(); }
  @Test public void testMemory375() { testComplete(); }
  @Test public void testMemory376() { testComplete(); }
  @Test public void testMemory377() { testComplete(); }
  @Test public void testMemory378() { testComplete(); }
  @Test public void testMemory379() { testComplete(); }
  @Test public void testMemory380() { testComplete(); }
  @Test public void testMemory381() { testComplete(); }
  @Test public void testMemory382() { testComplete(); }
  @Test public void testMemory383() { testComplete(); }
  @Test public void testMemory384() { testComplete(); }
  @Test public void testMemory385() { testComplete(); }
  @Test public void testMemory386() { testComplete(); }
  @Test public void testMemory387() { testComplete(); }
  @Test public void testMemory388() { testComplete(); }
  @Test public void testMemory389() { testComplete(); }
  @Test public void testMemory390() { testComplete(); }
  @Test public void testMemory391() { testComplete(); }
  @Test public void testMemory392() { testComplete(); }
  @Test public void testMemory393() { testComplete(); }
  @Test public void testMemory394() { testComplete(); }
  @Test public void testMemory395() { testComplete(); }
  @Test public void testMemory396() { testComplete(); }
  @Test public void testMemory397() { testComplete(); }
  @Test public void testMemory398() { testComplete(); }
  @Test public void testMemory399() { testComplete(); }
  @Test public void testMemory400() { testComplete(); }
  @Test public void testMemory401() { testComplete(); }
  @Test public void testMemory402() { testComplete(); }
  @Test public void testMemory403() { testComplete(); }
  @Test public void testMemory404() { testComplete(); }
  @Test public void testMemory405() { testComplete(); }
  @Test public void testMemory406() { testComplete(); }
  @Test public void testMemory407() { testComplete(); }
  @Test public void testMemory408() { testComplete(); }
  @Test public void testMemory409() { testComplete(); }
  @Test public void testMemory410() { testComplete(); }
  @Test public void testMemory411() { testComplete(); }
  @Test public void testMemory412() { testComplete(); }
  @Test public void testMemory413() { testComplete(); }
  @Test public void testMemory414() { testComplete(); }
  @Test public void testMemory415() { testComplete(); }
  @Test public void testMemory416() { testComplete(); }
  @Test public void testMemory417() { testComplete(); }
  @Test public void testMemory418() { testComplete(); }
  @Test public void testMemory419() { testComplete(); }
  @Test public void testMemory420() { testComplete(); }
  @Test public void testMemory421() { testComplete(); }
  @Test public void testMemory422() { testComplete(); }
  @Test public void testMemory423() { testComplete(); }
  @Test public void testMemory424() { testComplete(); }
  @Test public void testMemory425() { testComplete(); }
  @Test public void testMemory426() { testComplete(); }
  @Test public void testMemory427() { testComplete(); }
  @Test public void testMemory428() { testComplete(); }
  @Test public void testMemory429() { testComplete(); }
  @Test public void testMemory430() { testComplete(); }
  @Test public void testMemory431() { testComplete(); }
  @Test public void testMemory432() { testComplete(); }
  @Test public void testMemory433() { testComplete(); }
  @Test public void testMemory434() { testComplete(); }
  @Test public void testMemory435() { testComplete(); }
  @Test public void testMemory436() { testComplete(); }
  @Test public void testMemory437() { testComplete(); }
  @Test public void testMemory438() { testComplete(); }
  @Test public void testMemory439() { testComplete(); }
  @Test public void testMemory440() { testComplete(); }
  @Test public void testMemory441() { testComplete(); }
  @Test public void testMemory442() { testComplete(); }
  @Test public void testMemory443() { testComplete(); }
  @Test public void testMemory444() { testComplete(); }
  @Test public void testMemory445() { testComplete(); }
  @Test public void testMemory446() { testComplete(); }
  @Test public void testMemory447() { testComplete(); }
  @Test public void testMemory448() { testComplete(); }
  @Test public void testMemory449() { testComplete(); }
  @Test public void testMemory450() { testComplete(); }
  @Test public void testMemory451() { testComplete(); }
  @Test public void testMemory452() { testComplete(); }
  @Test public void testMemory453() { testComplete(); }
  @Test public void testMemory454() { testComplete(); }
  @Test public void testMemory455() { testComplete(); }
  @Test public void testMemory456() { testComplete(); }
  @Test public void testMemory457() { testComplete(); }
  @Test public void testMemory458() { testComplete(); }
  @Test public void testMemory459() { testComplete(); }
  @Test public void testMemory460() { testComplete(); }
  @Test public void testMemory461() { testComplete(); }
  @Test public void testMemory462() { testComplete(); }
  @Test public void testMemory463() { testComplete(); }
  @Test public void testMemory464() { testComplete(); }
  @Test public void testMemory465() { testComplete(); }
  @Test public void testMemory466() { testComplete(); }
  @Test public void testMemory467() { testComplete(); }
  @Test public void testMemory468() { testComplete(); }
  @Test public void testMemory469() { testComplete(); }
  @Test public void testMemory470() { testComplete(); }
  @Test public void testMemory471() { testComplete(); }
  @Test public void testMemory472() { testComplete(); }
  @Test public void testMemory473() { testComplete(); }
  @Test public void testMemory474() { testComplete(); }
  @Test public void testMemory475() { testComplete(); }
  @Test public void testMemory476() { testComplete(); }
  @Test public void testMemory477() { testComplete(); }
  @Test public void testMemory478() { testComplete(); }
  @Test public void testMemory479() { testComplete(); }
  @Test public void testMemory480() { testComplete(); }
  @Test public void testMemory481() { testComplete(); }
  @Test public void testMemory482() { testComplete(); }
  @Test public void testMemory483() { testComplete(); }
  @Test public void testMemory484() { testComplete(); }
  @Test public void testMemory485() { testComplete(); }
  @Test public void testMemory486() { testComplete(); }
  @Test public void testMemory487() { testComplete(); }
  @Test public void testMemory488() { testComplete(); }
  @Test public void testMemory489() { testComplete(); }
  @Test public void testMemory490() { testComplete(); }
  @Test public void testMemory491() { testComplete(); }
  @Test public void testMemory492() { testComplete(); }
  @Test public void testMemory493() { testComplete(); }
  @Test public void testMemory494() { testComplete(); }
  @Test public void testMemory495() { testComplete(); }
  @Test public void testMemory496() { testComplete(); }
  @Test public void testMemory497() { testComplete(); }
  @Test public void testMemory498() { testComplete(); }
  @Test public void testMemory499() { testComplete(); }
  @Test public void testMemory500() { testComplete(); }
  @Test public void testMemory501() { testComplete(); }
  @Test public void testMemory502() { testComplete(); }
  @Test public void testMemory503() { testComplete(); }
  @Test public void testMemory504() { testComplete(); }
  @Test public void testMemory505() { testComplete(); }
  @Test public void testMemory506() { testComplete(); }
  @Test public void testMemory507() { testComplete(); }
  @Test public void testMemory508() { testComplete(); }
  @Test public void testMemory509() { testComplete(); }
  @Test public void testMemory510() { testComplete(); }
  @Test public void testMemory511() { testComplete(); }
  @Test public void testMemory512() { testComplete(); }
  @Test public void testMemory513() { testComplete(); }
  @Test public void testMemory514() { testComplete(); }
  @Test public void testMemory515() { testComplete(); }
  @Test public void testMemory516() { testComplete(); }
  @Test public void testMemory517() { testComplete(); }
  @Test public void testMemory518() { testComplete(); }
  @Test public void testMemory519() { testComplete(); }
  @Test public void testMemory520() { testComplete(); }
  @Test public void testMemory521() { testComplete(); }
  @Test public void testMemory522() { testComplete(); }
  @Test public void testMemory523() { testComplete(); }
  @Test public void testMemory524() { testComplete(); }
  @Test public void testMemory525() { testComplete(); }
  @Test public void testMemory526() { testComplete(); }
  @Test public void testMemory527() { testComplete(); }
  @Test public void testMemory528() { testComplete(); }
  @Test public void testMemory529() { testComplete(); }
  @Test public void testMemory530() { testComplete(); }
  @Test public void testMemory531() { testComplete(); }
  @Test public void testMemory532() { testComplete(); }
  @Test public void testMemory533() { testComplete(); }
  @Test public void testMemory534() { testComplete(); }
  @Test public void testMemory535() { testComplete(); }
  @Test public void testMemory536() { testComplete(); }
  @Test public void testMemory537() { testComplete(); }
  @Test public void testMemory538() { testComplete(); }
  @Test public void testMemory539() { testComplete(); }
  @Test public void testMemory540() { testComplete(); }
  @Test public void testMemory541() { testComplete(); }
  @Test public void testMemory542() { testComplete(); }
  @Test public void testMemory543() { testComplete(); }
  @Test public void testMemory544() { testComplete(); }
  @Test public void testMemory545() { testComplete(); }
  @Test public void testMemory546() { testComplete(); }
  @Test public void testMemory547() { testComplete(); }
  @Test public void testMemory548() { testComplete(); }
  @Test public void testMemory549() { testComplete(); }
  @Test public void testMemory550() { testComplete(); }
  @Test public void testMemory551() { testComplete(); }
  @Test public void testMemory552() { testComplete(); }
  @Test public void testMemory553() { testComplete(); }
  @Test public void testMemory554() { testComplete(); }
  @Test public void testMemory555() { testComplete(); }
  @Test public void testMemory556() { testComplete(); }
  @Test public void testMemory557() { testComplete(); }
  @Test public void testMemory558() { testComplete(); }
  @Test public void testMemory559() { testComplete(); }
  @Test public void testMemory560() { testComplete(); }
  @Test public void testMemory561() { testComplete(); }
  @Test public void testMemory562() { testComplete(); }
  @Test public void testMemory563() { testComplete(); }
  @Test public void testMemory564() { testComplete(); }
  @Test public void testMemory565() { testComplete(); }
  @Test public void testMemory566() { testComplete(); }
  @Test public void testMemory567() { testComplete(); }
  @Test public void testMemory568() { testComplete(); }
  @Test public void testMemory569() { testComplete(); }
  @Test public void testMemory570() { testComplete(); }
  @Test public void testMemory571() { testComplete(); }
  @Test public void testMemory572() { testComplete(); }
  @Test public void testMemory573() { testComplete(); }
  @Test public void testMemory574() { testComplete(); }
  @Test public void testMemory575() { testComplete(); }
  @Test public void testMemory576() { testComplete(); }
  @Test public void testMemory577() { testComplete(); }
  @Test public void testMemory578() { testComplete(); }
  @Test public void testMemory579() { testComplete(); }
  @Test public void testMemory580() { testComplete(); }
  @Test public void testMemory581() { testComplete(); }
  @Test public void testMemory582() { testComplete(); }
  @Test public void testMemory583() { testComplete(); }
  @Test public void testMemory584() { testComplete(); }
  @Test public void testMemory585() { testComplete(); }
  @Test public void testMemory586() { testComplete(); }
  @Test public void testMemory587() { testComplete(); }
  @Test public void testMemory588() { testComplete(); }
  @Test public void testMemory589() { testComplete(); }
  @Test public void testMemory590() { testComplete(); }
  @Test public void testMemory591() { testComplete(); }
  @Test public void testMemory592() { testComplete(); }
  @Test public void testMemory593() { testComplete(); }
  @Test public void testMemory594() { testComplete(); }
  @Test public void testMemory595() { testComplete(); }
  @Test public void testMemory596() { testComplete(); }
  @Test public void testMemory597() { testComplete(); }
  @Test public void testMemory598() { testComplete(); }
  @Test public void testMemory599() { testComplete(); }
  @Test public void testMemory600() { testComplete(); }
  @Test public void testMemory601() { testComplete(); }
  @Test public void testMemory602() { testComplete(); }
  @Test public void testMemory603() { testComplete(); }
  @Test public void testMemory604() { testComplete(); }
  @Test public void testMemory605() { testComplete(); }
  @Test public void testMemory606() { testComplete(); }
  @Test public void testMemory607() { testComplete(); }
  @Test public void testMemory608() { testComplete(); }
  @Test public void testMemory609() { testComplete(); }
  @Test public void testMemory610() { testComplete(); }
  @Test public void testMemory611() { testComplete(); }
  @Test public void testMemory612() { testComplete(); }
  @Test public void testMemory613() { testComplete(); }
  @Test public void testMemory614() { testComplete(); }
  @Test public void testMemory615() { testComplete(); }
  @Test public void testMemory616() { testComplete(); }
  @Test public void testMemory617() { testComplete(); }
  @Test public void testMemory618() { testComplete(); }
  @Test public void testMemory619() { testComplete(); }
  @Test public void testMemory620() { testComplete(); }
  @Test public void testMemory621() { testComplete(); }
  @Test public void testMemory622() { testComplete(); }
  @Test public void testMemory623() { testComplete(); }
  @Test public void testMemory624() { testComplete(); }
  @Test public void testMemory625() { testComplete(); }
  @Test public void testMemory626() { testComplete(); }
  @Test public void testMemory627() { testComplete(); }
  @Test public void testMemory628() { testComplete(); }
  @Test public void testMemory629() { testComplete(); }
  @Test public void testMemory630() { testComplete(); }
  @Test public void testMemory631() { testComplete(); }
  @Test public void testMemory632() { testComplete(); }
  @Test public void testMemory633() { testComplete(); }
  @Test public void testMemory634() { testComplete(); }
  @Test public void testMemory635() { testComplete(); }
  @Test public void testMemory636() { testComplete(); }
  @Test public void testMemory637() { testComplete(); }
  @Test public void testMemory638() { testComplete(); }
  @Test public void testMemory639() { testComplete(); }
  @Test public void testMemory640() { testComplete(); }
  @Test public void testMemory641() { testComplete(); }
  @Test public void testMemory642() { testComplete(); }
  @Test public void testMemory643() { testComplete(); }
  @Test public void testMemory644() { testComplete(); }
  @Test public void testMemory645() { testComplete(); }
  @Test public void testMemory646() { testComplete(); }
  @Test public void testMemory647() { testComplete(); }
  @Test public void testMemory648() { testComplete(); }
  @Test public void testMemory649() { testComplete(); }
  @Test public void testMemory650() { testComplete(); }
  @Test public void testMemory651() { testComplete(); }
  @Test public void testMemory652() { testComplete(); }
  @Test public void testMemory653() { testComplete(); }
  @Test public void testMemory654() { testComplete(); }
  @Test public void testMemory655() { testComplete(); }
  @Test public void testMemory656() { testComplete(); }
  @Test public void testMemory657() { testComplete(); }
  @Test public void testMemory658() { testComplete(); }
  @Test public void testMemory659() { testComplete(); }
  @Test public void testMemory660() { testComplete(); }
  @Test public void testMemory661() { testComplete(); }
  @Test public void testMemory662() { testComplete(); }
  @Test public void testMemory663() { testComplete(); }
  @Test public void testMemory664() { testComplete(); }
  @Test public void testMemory665() { testComplete(); }
  @Test public void testMemory666() { testComplete(); }
  @Test public void testMemory667() { testComplete(); }
  @Test public void testMemory668() { testComplete(); }
  @Test public void testMemory669() { testComplete(); }
  @Test public void testMemory670() { testComplete(); }
  @Test public void testMemory671() { testComplete(); }
  @Test public void testMemory672() { testComplete(); }
  @Test public void testMemory673() { testComplete(); }
  @Test public void testMemory674() { testComplete(); }
  @Test public void testMemory675() { testComplete(); }
  @Test public void testMemory676() { testComplete(); }
  @Test public void testMemory677() { testComplete(); }
  @Test public void testMemory678() { testComplete(); }
  @Test public void testMemory679() { testComplete(); }
  @Test public void testMemory680() { testComplete(); }
  @Test public void testMemory681() { testComplete(); }
  @Test public void testMemory682() { testComplete(); }
  @Test public void testMemory683() { testComplete(); }
  @Test public void testMemory684() { testComplete(); }
  @Test public void testMemory685() { testComplete(); }
  @Test public void testMemory686() { testComplete(); }
  @Test public void testMemory687() { testComplete(); }
  @Test public void testMemory688() { testComplete(); }
  @Test public void testMemory689() { testComplete(); }
  @Test public void testMemory690() { testComplete(); }
  @Test public void testMemory691() { testComplete(); }
  @Test public void testMemory692() { testComplete(); }
  @Test public void testMemory693() { testComplete(); }
  @Test public void testMemory694() { testComplete(); }
  @Test public void testMemory695() { testComplete(); }
  @Test public void testMemory696() { testComplete(); }
  @Test public void testMemory697() { testComplete(); }
  @Test public void testMemory698() { testComplete(); }
  @Test public void testMemory699() { testComplete(); }
  @Test public void testMemory700() { testComplete(); }
  @Test public void testMemory701() { testComplete(); }
  @Test public void testMemory702() { testComplete(); }
  @Test public void testMemory703() { testComplete(); }
  @Test public void testMemory704() { testComplete(); }
  @Test public void testMemory705() { testComplete(); }
  @Test public void testMemory706() { testComplete(); }
  @Test public void testMemory707() { testComplete(); }
  @Test public void testMemory708() { testComplete(); }
  @Test public void testMemory709() { testComplete(); }
  @Test public void testMemory710() { testComplete(); }
  @Test public void testMemory711() { testComplete(); }
  @Test public void testMemory712() { testComplete(); }
  @Test public void testMemory713() { testComplete(); }
  @Test public void testMemory714() { testComplete(); }
  @Test public void testMemory715() { testComplete(); }
  @Test public void testMemory716() { testComplete(); }
  @Test public void testMemory717() { testComplete(); }
  @Test public void testMemory718() { testComplete(); }
  @Test public void testMemory719() { testComplete(); }
  @Test public void testMemory720() { testComplete(); }
  @Test public void testMemory721() { testComplete(); }
  @Test public void testMemory722() { testComplete(); }
  @Test public void testMemory723() { testComplete(); }
  @Test public void testMemory724() { testComplete(); }
  @Test public void testMemory725() { testComplete(); }
  @Test public void testMemory726() { testComplete(); }
  @Test public void testMemory727() { testComplete(); }
  @Test public void testMemory728() { testComplete(); }
  @Test public void testMemory729() { testComplete(); }
  @Test public void testMemory730() { testComplete(); }
  @Test public void testMemory731() { testComplete(); }
  @Test public void testMemory732() { testComplete(); }
  @Test public void testMemory733() { testComplete(); }
  @Test public void testMemory734() { testComplete(); }
  @Test public void testMemory735() { testComplete(); }
  @Test public void testMemory736() { testComplete(); }
  @Test public void testMemory737() { testComplete(); }
  @Test public void testMemory738() { testComplete(); }
  @Test public void testMemory739() { testComplete(); }
  @Test public void testMemory740() { testComplete(); }
  @Test public void testMemory741() { testComplete(); }
  @Test public void testMemory742() { testComplete(); }
  @Test public void testMemory743() { testComplete(); }
  @Test public void testMemory744() { testComplete(); }
  @Test public void testMemory745() { testComplete(); }
  @Test public void testMemory746() { testComplete(); }
  @Test public void testMemory747() { testComplete(); }
  @Test public void testMemory748() { testComplete(); }
  @Test public void testMemory749() { testComplete(); }
  @Test public void testMemory750() { testComplete(); }
  @Test public void testMemory751() { testComplete(); }
  @Test public void testMemory752() { testComplete(); }
  @Test public void testMemory753() { testComplete(); }
  @Test public void testMemory754() { testComplete(); }
  @Test public void testMemory755() { testComplete(); }
  @Test public void testMemory756() { testComplete(); }
  @Test public void testMemory757() { testComplete(); }
  @Test public void testMemory758() { testComplete(); }
  @Test public void testMemory759() { testComplete(); }
  @Test public void testMemory760() { testComplete(); }
  @Test public void testMemory761() { testComplete(); }
  @Test public void testMemory762() { testComplete(); }
  @Test public void testMemory763() { testComplete(); }
  @Test public void testMemory764() { testComplete(); }
  @Test public void testMemory765() { testComplete(); }
  @Test public void testMemory766() { testComplete(); }
  @Test public void testMemory767() { testComplete(); }
  @Test public void testMemory768() { testComplete(); }
  @Test public void testMemory769() { testComplete(); }
  @Test public void testMemory770() { testComplete(); }
  @Test public void testMemory771() { testComplete(); }
  @Test public void testMemory772() { testComplete(); }
  @Test public void testMemory773() { testComplete(); }
  @Test public void testMemory774() { testComplete(); }
  @Test public void testMemory775() { testComplete(); }
  @Test public void testMemory776() { testComplete(); }
  @Test public void testMemory777() { testComplete(); }
  @Test public void testMemory778() { testComplete(); }
  @Test public void testMemory779() { testComplete(); }
  @Test public void testMemory780() { testComplete(); }
  @Test public void testMemory781() { testComplete(); }
  @Test public void testMemory782() { testComplete(); }
  @Test public void testMemory783() { testComplete(); }
  @Test public void testMemory784() { testComplete(); }
  @Test public void testMemory785() { testComplete(); }
  @Test public void testMemory786() { testComplete(); }
  @Test public void testMemory787() { testComplete(); }
  @Test public void testMemory788() { testComplete(); }
  @Test public void testMemory789() { testComplete(); }
  @Test public void testMemory790() { testComplete(); }
  @Test public void testMemory791() { testComplete(); }
  @Test public void testMemory792() { testComplete(); }
  @Test public void testMemory793() { testComplete(); }
  @Test public void testMemory794() { testComplete(); }
  @Test public void testMemory795() { testComplete(); }
  @Test public void testMemory796() { testComplete(); }
  @Test public void testMemory797() { testComplete(); }
  @Test public void testMemory798() { testComplete(); }
  @Test public void testMemory799() { testComplete(); }
  @Test public void testMemory800() { testComplete(); }
  @Test public void testMemory801() { testComplete(); }
  @Test public void testMemory802() { testComplete(); }
  @Test public void testMemory803() { testComplete(); }
  @Test public void testMemory804() { testComplete(); }
  @Test public void testMemory805() { testComplete(); }
  @Test public void testMemory806() { testComplete(); }
  @Test public void testMemory807() { testComplete(); }
  @Test public void testMemory808() { testComplete(); }
  @Test public void testMemory809() { testComplete(); }
  @Test public void testMemory810() { testComplete(); }
  @Test public void testMemory811() { testComplete(); }
  @Test public void testMemory812() { testComplete(); }
  @Test public void testMemory813() { testComplete(); }
  @Test public void testMemory814() { testComplete(); }
  @Test public void testMemory815() { testComplete(); }
  @Test public void testMemory816() { testComplete(); }
  @Test public void testMemory817() { testComplete(); }
  @Test public void testMemory818() { testComplete(); }
  @Test public void testMemory819() { testComplete(); }
  @Test public void testMemory820() { testComplete(); }
  @Test public void testMemory821() { testComplete(); }
  @Test public void testMemory822() { testComplete(); }
  @Test public void testMemory823() { testComplete(); }
  @Test public void testMemory824() { testComplete(); }
  @Test public void testMemory825() { testComplete(); }
  @Test public void testMemory826() { testComplete(); }
  @Test public void testMemory827() { testComplete(); }
  @Test public void testMemory828() { testComplete(); }
  @Test public void testMemory829() { testComplete(); }
  @Test public void testMemory830() { testComplete(); }
  @Test public void testMemory831() { testComplete(); }
  @Test public void testMemory832() { testComplete(); }
  @Test public void testMemory833() { testComplete(); }
  @Test public void testMemory834() { testComplete(); }
  @Test public void testMemory835() { testComplete(); }
  @Test public void testMemory836() { testComplete(); }
  @Test public void testMemory837() { testComplete(); }
  @Test public void testMemory838() { testComplete(); }
  @Test public void testMemory839() { testComplete(); }
  @Test public void testMemory840() { testComplete(); }
  @Test public void testMemory841() { testComplete(); }
  @Test public void testMemory842() { testComplete(); }
  @Test public void testMemory843() { testComplete(); }
  @Test public void testMemory844() { testComplete(); }
  @Test public void testMemory845() { testComplete(); }
  @Test public void testMemory846() { testComplete(); }
  @Test public void testMemory847() { testComplete(); }
  @Test public void testMemory848() { testComplete(); }
  @Test public void testMemory849() { testComplete(); }
  @Test public void testMemory850() { testComplete(); }
  @Test public void testMemory851() { testComplete(); }
  @Test public void testMemory852() { testComplete(); }
  @Test public void testMemory853() { testComplete(); }
  @Test public void testMemory854() { testComplete(); }
  @Test public void testMemory855() { testComplete(); }
  @Test public void testMemory856() { testComplete(); }
  @Test public void testMemory857() { testComplete(); }
  @Test public void testMemory858() { testComplete(); }
  @Test public void testMemory859() { testComplete(); }
  @Test public void testMemory860() { testComplete(); }
  @Test public void testMemory861() { testComplete(); }
  @Test public void testMemory862() { testComplete(); }
  @Test public void testMemory863() { testComplete(); }
  @Test public void testMemory864() { testComplete(); }
  @Test public void testMemory865() { testComplete(); }
  @Test public void testMemory866() { testComplete(); }
  @Test public void testMemory867() { testComplete(); }
  @Test public void testMemory868() { testComplete(); }
  @Test public void testMemory869() { testComplete(); }
  @Test public void testMemory870() { testComplete(); }
  @Test public void testMemory871() { testComplete(); }
  @Test public void testMemory872() { testComplete(); }
  @Test public void testMemory873() { testComplete(); }
  @Test public void testMemory874() { testComplete(); }
  @Test public void testMemory875() { testComplete(); }
  @Test public void testMemory876() { testComplete(); }
  @Test public void testMemory877() { testComplete(); }
  @Test public void testMemory878() { testComplete(); }
  @Test public void testMemory879() { testComplete(); }
  @Test public void testMemory880() { testComplete(); }
  @Test public void testMemory881() { testComplete(); }
  @Test public void testMemory882() { testComplete(); }
  @Test public void testMemory883() { testComplete(); }
  @Test public void testMemory884() { testComplete(); }
  @Test public void testMemory885() { testComplete(); }
  @Test public void testMemory886() { testComplete(); }
  @Test public void testMemory887() { testComplete(); }
  @Test public void testMemory888() { testComplete(); }
  @Test public void testMemory889() { testComplete(); }
  @Test public void testMemory890() { testComplete(); }
  @Test public void testMemory891() { testComplete(); }
  @Test public void testMemory892() { testComplete(); }
  @Test public void testMemory893() { testComplete(); }
  @Test public void testMemory894() { testComplete(); }
  @Test public void testMemory895() { testComplete(); }
  @Test public void testMemory896() { testComplete(); }
  @Test public void testMemory897() { testComplete(); }
  @Test public void testMemory898() { testComplete(); }
  @Test public void testMemory899() { testComplete(); }
  @Test public void testMemory900() { testComplete(); }
  @Test public void testMemory901() { testComplete(); }
  @Test public void testMemory902() { testComplete(); }
  @Test public void testMemory903() { testComplete(); }
  @Test public void testMemory904() { testComplete(); }
  @Test public void testMemory905() { testComplete(); }
  @Test public void testMemory906() { testComplete(); }
  @Test public void testMemory907() { testComplete(); }
  @Test public void testMemory908() { testComplete(); }
  @Test public void testMemory909() { testComplete(); }
  @Test public void testMemory910() { testComplete(); }
  @Test public void testMemory911() { testComplete(); }
  @Test public void testMemory912() { testComplete(); }
  @Test public void testMemory913() { testComplete(); }
  @Test public void testMemory914() { testComplete(); }
  @Test public void testMemory915() { testComplete(); }
  @Test public void testMemory916() { testComplete(); }
  @Test public void testMemory917() { testComplete(); }
  @Test public void testMemory918() { testComplete(); }
  @Test public void testMemory919() { testComplete(); }
  @Test public void testMemory920() { testComplete(); }
  @Test public void testMemory921() { testComplete(); }
  @Test public void testMemory922() { testComplete(); }
  @Test public void testMemory923() { testComplete(); }
  @Test public void testMemory924() { testComplete(); }
  @Test public void testMemory925() { testComplete(); }
  @Test public void testMemory926() { testComplete(); }
  @Test public void testMemory927() { testComplete(); }
  @Test public void testMemory928() { testComplete(); }
  @Test public void testMemory929() { testComplete(); }
  @Test public void testMemory930() { testComplete(); }
  @Test public void testMemory931() { testComplete(); }
  @Test public void testMemory932() { testComplete(); }
  @Test public void testMemory933() { testComplete(); }
  @Test public void testMemory934() { testComplete(); }
  @Test public void testMemory935() { testComplete(); }
  @Test public void testMemory936() { testComplete(); }
  @Test public void testMemory937() { testComplete(); }
  @Test public void testMemory938() { testComplete(); }
  @Test public void testMemory939() { testComplete(); }
  @Test public void testMemory940() { testComplete(); }
  @Test public void testMemory941() { testComplete(); }
  @Test public void testMemory942() { testComplete(); }
  @Test public void testMemory943() { testComplete(); }
  @Test public void testMemory944() { testComplete(); }
  @Test public void testMemory945() { testComplete(); }
  @Test public void testMemory946() { testComplete(); }
  @Test public void testMemory947() { testComplete(); }
  @Test public void testMemory948() { testComplete(); }
  @Test public void testMemory949() { testComplete(); }
  @Test public void testMemory950() { testComplete(); }
  @Test public void testMemory951() { testComplete(); }
  @Test public void testMemory952() { testComplete(); }
  @Test public void testMemory953() { testComplete(); }
  @Test public void testMemory954() { testComplete(); }
  @Test public void testMemory955() { testComplete(); }
  @Test public void testMemory956() { testComplete(); }
  @Test public void testMemory957() { testComplete(); }
  @Test public void testMemory958() { testComplete(); }
  @Test public void testMemory959() { testComplete(); }
  @Test public void testMemory960() { testComplete(); }
  @Test public void testMemory961() { testComplete(); }
  @Test public void testMemory962() { testComplete(); }
  @Test public void testMemory963() { testComplete(); }
  @Test public void testMemory964() { testComplete(); }
  @Test public void testMemory965() { testComplete(); }
  @Test public void testMemory966() { testComplete(); }
  @Test public void testMemory967() { testComplete(); }
  @Test public void testMemory968() { testComplete(); }
  @Test public void testMemory969() { testComplete(); }
  @Test public void testMemory970() { testComplete(); }
  @Test public void testMemory971() { testComplete(); }
  @Test public void testMemory972() { testComplete(); }
  @Test public void testMemory973() { testComplete(); }
  @Test public void testMemory974() { testComplete(); }
  @Test public void testMemory975() { testComplete(); }
  @Test public void testMemory976() { testComplete(); }
  @Test public void testMemory977() { testComplete(); }
  @Test public void testMemory978() { testComplete(); }
  @Test public void testMemory979() { testComplete(); }
  @Test public void testMemory980() { testComplete(); }
  @Test public void testMemory981() { testComplete(); }
  @Test public void testMemory982() { testComplete(); }
  @Test public void testMemory983() { testComplete(); }
  @Test public void testMemory984() { testComplete(); }
  @Test public void testMemory985() { testComplete(); }
  @Test public void testMemory986() { testComplete(); }
  @Test public void testMemory987() { testComplete(); }
  @Test public void testMemory988() { testComplete(); }
  @Test public void testMemory989() { testComplete(); }
  @Test public void testMemory990() { testComplete(); }
  @Test public void testMemory991() { testComplete(); }
  @Test public void testMemory992() { testComplete(); }
  @Test public void testMemory993() { testComplete(); }
  @Test public void testMemory994() { testComplete(); }
  @Test public void testMemory995() { testComplete(); }
  @Test public void testMemory996() { testComplete(); }
  @Test public void testMemory997() { testComplete(); }
  @Test public void testMemory998() { testComplete(); }
  @Test public void testMemory999() { testComplete(); }

  @Override
  public void start() {
    // Make sure we call initialize() - this sets up the assert stuff so assert functionality works correctly
    initialize();
    // Deploy the module - the System property `vertx.modulename` will contain the name of the module so you
    // don't have to hardecode it in your tests
    container.deployModule(System.getProperty("vertx.modulename"), new AsyncResultHandler<String>() {
      @Override
      public void handle(AsyncResult<String> asyncResult) {
      // Deployment is asynchronous and this this handler will be called when it's complete (or failed)
      if (asyncResult.failed()) {
        container.logger().error(asyncResult.cause());
      }
      assertTrue(asyncResult.succeeded());
      assertNotNull("deploymentID should not be null", asyncResult.result());
      // If deployed correctly then start the tests!
      startTests();
      }
    });
  }

}
